/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appman_rmswrapper_pbs_drmaa_SessionImpl */

#ifndef _Included_appman_rmswrapper_pbs_drmaa_SessionImpl
#define _Included_appman_rmswrapper_pbs_drmaa_SessionImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeControl
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeControl
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeExit
  (JNIEnv *, jobject);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeGetContact
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeGetContact
  (JNIEnv *, jobject);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeGetDRMSInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeGetDRMSInfo
  (JNIEnv *, jobject);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeGetJobProgramStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeGetJobProgramStatus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeRunBulkJobs
 * Signature: (IIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeRunBulkJobs
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeRunJob
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeRunJob
  (JNIEnv *, jobject, jint);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeSynchronize
 * Signature: ([Ljava/lang/String;JZ)V
 */
JNIEXPORT void JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeSynchronize
  (JNIEnv *, jobject, jobjectArray, jlong, jboolean);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeWait
 * Signature: (Ljava/lang/String;J)Lappman/rmswrapper/pbs/drmaa/JobInfoImpl;
 */
JNIEXPORT jobject JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeWait
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeAllocateJobTemplate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeAllocateJobTemplate
  (JNIEnv *, jobject);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeSetAttributeValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeSetAttributeValue
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeSetAttributeValues
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeSetAttributeValues
  (JNIEnv *, jobject, jint, jstring, jobjectArray);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeGetAttributeNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeGetAttributeNames
  (JNIEnv *, jobject, jint);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeGetAttribute
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeGetAttribute
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     appman_rmswrapper_pbs_drmaa_SessionImpl
 * Method:    nativeDeleteJobTemplate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_appman_rmswrapper_pbs_drmaa_SessionImpl_nativeDeleteJobTemplate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
