/* Generated By:JJTree: Do not edit this line. SimpleParserTreeConstants.java */

package appman.parser;

public interface SimpleParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTTASK = 2;
  public int JJTFOREACHNODE = 3;
  public int JJTASSIGNMENT = 4;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Task",
    "ForeachNode",
    "Assignment",
  };
}
