package appman.parser;
// Generated By:JJTree: Do not edit this line. ASTRoot.java 
/** Generated By:JJTree*/

public class ASTRoot extends SimpleNode {
  public ASTRoot(int id) {
    super(id);
  }

  public ASTRoot(SimpleParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
