/* Generated By:JJTree&JavaCC: Do not edit this line. SimpleParserConstants.java */
package appman.parser;

public interface SimpleParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int GRAPH = 8;
  int INDEP = 9;
  int LOW = 10;
  int HIGH = 11;
  int TASK = 12;
  int EXECUTABLE = 13;
  int INPUT = 14;
  int OUTPUT = 15;
  int CAPACITY = 16;
  int DONE = 17;
  int FOREACH = 18;
  int IN = 19;
  int TRANSIENT = 20;
  int LISTDELIMITER = 21;
  int constant = 22;
  int plain_constant = 23;
  int number = 24;
  int var = 25;
  int character = 26;
  int string = 27;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"#\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 7>",
    "\"graph\"",
    "\"independent\"",
    "\"low-coupled\"",
    "\"high-coupled\"",
    "\"task\"",
    "\"-e\"",
    "\"-i\"",
    "\"-o\"",
    "\"-c\"",
    "\"done\"",
    "\"foreach\"",
    "\"in\"",
    "\"transient\"",
    "\";\"",
    "<constant>",
    "<plain_constant>",
    "<number>",
    "<var>",
    "<character>",
    "<string>",
    "\"{\"",
    "\"}\"",
    "\"..\"",
    "\"=\"",
    "\"/\"",
    "\"*\"",
    "\"^\"",
    "\"+\"",
    "\"-\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
  };

}
